export const ROUTE_CONSTANTS = {
  HOME: '/',
  REGISTRATION: '/registration',
  REGISTRATION_ADD_INFO: '/registration/add-info',
  MAIN_PAGE: '/home',
  MAIN_PAGE_DISH: '/home/dishes',
  MAIN_PAGE_MENU: '/home/menus',
  ERROR: '/error',
  PROFILE: '/profile',
  PROFILE_LOGOUT: '/profile/logout',
  PROFILE_EDIT_USER: '/profile/edit-user',
  PROFILE_CHANGE_PASS: '/profile/change-password',
  PROFILE_CHANGE_ADDRESS: '/profile/change-address',
  CART: 'cart',
} as const;
